// Re-export all shared types for frontend use
export type {
  Account,
  Income,
  Expense,
  ExpenseCategory,
  Debt,
  DebtDealPeriod,
  SavingsGoal,
  SavingsTransaction,
  SavingsTransactionType,
  MonthLock,
  RepaymentRow,
  DebtPayoffSummary,
  CategoryBreakdown,
  BudgetSummary,
  HouseholdOverview,
  Theme,
  // Auth types
  User,
  Household,
  HouseholdMember,
  HouseholdRole,
  SystemRole,
  SessionInfo,
  LoginRequest,
  RegisterRequest,
  TotpSetupResponse,
  AuthStatusResponse,
  // Admin types
  AdminUser,
  SmtpConfig,
  OidcConfig,
  LoggingConfig,
  RegistrationConfig,
  AutoBackupConfig,
  AuditLogEntry,
  PaginatedResponse,
  VersionInfo,
  // Reports types
  ReportRange,
  MonthlyReportRow,
  DebtPerDebtBreakdown,
  DebtProjectionPoint,
  DebtPayoffTimelinePoint,
  DebtPayoffStrategyResult,
  UpcomingBillSource,
  UpcomingBillStatus,
  UpcomingBillOccurrence,
  UpcomingBillsSummary,
  UpcomingBillsReportResponse,
} from '../../shared/types';

export { EXPENSE_CATEGORIES } from '../../shared/types';
